POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "teste 2",
  "description": "descrição do teste",
  "maximunAttendees": 1
}

###

POST http://localhost:3333/events/67c61d55-607a-4c46-aaaf-995b68f9e98f/attendee
Content-Type: application/json

{
  "name": "john",
  "email": "john@gmail.com"
}
