POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "teste",
  "description": "descrição do teste",
  "maximunAttendees": 100
}

###

POST http://localhost:3333/events/532dac09-3a25-472e-b6c0-543a6919ef0d/attendee
Content-Type: application/json

{
  "name": "José",
  "email": "jose@gmail.com"
}
